- name: Install Shibboleth apt packages
  apt: name={{ item }} state=present
  with_items:
    - shibboleth-sp2-utils  # sp
    - shibboleth-sp2-common # sp
    - libshibsp7            # sp

# - name: Install IdP Virtualhost configuration
  # template:
    # src: "roles/{{ role_name }}/templates/idp-{{ servlet_container }}.conf"
    # dest: /etc/nginx/sites-available/{{ idp_fqdn }}.conf

# - name: Enable IdP Virtualhost
  # command: ln -s /etc/nginx/sites-available/{{ idp_fqdn }}.conf /etc/apache2/sites-enabled/

# - name: Enable NginX custom parameters
  # copy: roles/{{ role_name }}/files/{{ item }} /etc/nginx/conf.d/
  # with_items:
    # - ssl_hardening.conf
  
# - name: Restart Nginx
  # service: name=nginx state=restarted enabled=yes
