# https://wiki.shibboleth.net/confluence/display/IDP30/Installation
# ansible-playbook playbook.yml -i hosts -v
# or if you want to run specifieds roles:
# ansible-playbook playbook.yml -i hosts -v --tag common
# inspired by: https://github.com/ConsortiumGARR/idem-tutorials/blob/master/idem-fedops/HOWTO-Shibboleth/Identity%20Provider/Ubuntu/HOWTO%20Install%20and%20Configure%20a%20Shibboleth%20IdP%20v3.2.1%20on%20Ubuntu%20Linux%20LTS%2016.04%20with%20Apache2%20%2B%20Jetty9.md
---
- name: Install Shibboleth IDP and SP
  hosts: all
  become: yes
  vars:
    hostname: testunical
    domain1: it
    domain: "{{ hostname }}.{{ domain1 }}"
    
    ldap_ip:  "192.168.3.63"
    idp_ip:   "192.168.3.63"
    sp_ip:    "192.168.3.63"

    # Commons
    cert_path: "/etc/ssl/certs/{{ domain }}"
    tmp_upload_dir: "/tmp/ansible-shibboleth-idp-sp-setup"

    # LDAP configuration
    ldap_fqdn: "ldap.testunical.it"
    ldap_basedc: "dc={{ hostname }},dc={{ domain1 }}"
    ldap_binddn: "uid=idp,ou=applications,{{ ldap_basedc }}"
    ldap_pw: idpsecret
    ldap_basedn: "ou=people,{{ ldap_basedc }}"
    # remember to copy slapds' public cert, as slapd-cert.pem, in roles/common/files/certs/
    ldap_cert: slapd-cert.pem
    
    # Jetty configuration
    jetty_distribution: jetty-distribution-9.4.8.v20171121
    jetty_pkg: "{{ jetty_distribution }}.tar.gz"
    jetty_path : /opt/jetty
    # jetty_admin_pw: jettysecret
    # jetty_manager_pw: jettysecret
    jetty_ram: 384m

    # Shibboleth IDP
    shib_idp_version: "3.3.2"
    shib_idp_package: "shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
    shib_dest_dir: "/opt"
    idp_path: "{{ shib_dest_dir }}/shibboleth-idp"
    shib_setup_folder: "{{ shib_dest_dir }}/shibboleth-identity-provider-{{ shib_idp_version }}"
    idp_dl_url: "https://shibboleth.net/downloads/identity-provider/{{ shib_idp_version }}/{{ shib_idp_package }}"
    idp_web_folder: /idp/shibboleth
    idp_entity_id: "https://{{ idp_fqdn }}{{ idp_web_folder }}"
    idp_fqdn: "idp.{{ domain }}"
    idp_secret:   idpsecret
    idp_admin_email: "root@{{ idp_fqdn }}"
    
    # Shibboleth IDP RDBMS per persistentID
    idp_rdbms_dbname: shibboleth
    idp_rdbms_user: "{{ idp_rdbms_dbname }}"
    idp_rdbms_pw: "{{ idp_secret }}"

    # Shibboleth SP
    sp_fqdn: "sp.{{ domain }}"

  roles:
    # - { role: uninstall, tags: ["uninstall"] }
    
    - { role: common, tags: ["common"] }
    - { role: jetty, tags: ["jetty"] }
    - { role: mysql, tags: ["mysql"] }
    - { role: shib3idp_install, tags: ["shib3idp_install"] }
    - { role: apache2, tags: ["apache2"] }
    - { role: shib3idp_configure, tags: ["shib3idp_configure"] }
    
    - { role: mod-shib2, tags: ["shib2"] }  
