# ansible-playbook playbook.yml -i hosts -v
# or if you want to run specifieds roles:
# ansible-playbook playbook.yml -i hosts -v --tag common

---
- name: Install IdP Course VM
  hosts: all
  become: yes
  vars:
    name:   testunical
    domain1: it
    domain: "{{ name }}.{{ domain1 }}"
    
    idp_ip: "10.0.7.1"
    sp_ip:  "10.0.7.10"
    
    ldap_basedc: "dc={{ name }},dc={{ domain1 }}"
    ldap_basedn: "ou=people,dc={{ name }},dc={{ domain1 }}"
    #ldap_binddn: "cn=search,ou=system,dc={{ name }},dc={{ domain1 }}"
    ldap_pw: password
    # ldap_bind: localhost
    cert_path: /etc/ssl/certs/shibboleth
    
    idp_dl_url: https://shibboleth.net/downloads/identity-provider/3.3.2/shibboleth-identity-provider-3.3.2.tar.gz
    idp_fqdn: "idp.{{ domain }}"
    idp_path: /opt/shibboleth-idp
    idp_pw: password

    sp_fqdn: "sp.{{ domain }}"
    
    # mysql_pw: password
    # idpdb_user: shibboleth
    # idpdb_pw: password
    
    tomcat_admin_pw: password
    tomcat_manager_pw: password
        
  roles:
    - { role: common, tags: ["common"] }
    - { role: tomcat, tags: ["tomcat"] }
    - { role: slapd, tags: ["slapd"] }
    - { role: shib3idp, tags: ["shib3idp"] }
    - { role: apache2, tags: ["apache2"] }
    - { role: mod-shib2, tags: ["shib2"] }  
    - { role: mysql, tags: ["mysql"] }      

