# https://wiki.shibboleth.net/confluence/display/IDP30/Installation
# ansible-playbook playbook.yml -i hosts -v
# or if you want to run specifieds roles:
# ansible-playbook playbook.yml -i hosts -v --tag common
# inspired by: https://github.com/ConsortiumGARR/idem-tutorials/blob/master/idem-fedops/HOWTO-Shibboleth/Identity%20Provider/Ubuntu/HOWTO%20Install%20and%20Configure%20a%20Shibboleth%20IdP%20v3.2.1%20on%20Ubuntu%20Linux%20LTS%2016.04%20with%20Apache2%20%2B%20Jetty9.md
---
- name: Install Shibboleth IDP and SP
  hosts: all
  become: yes
  vars:
    domain2: testunical
    domain1: it
    domain: "{{ domain2 }}.{{ domain1 }}"

    server_admin: "root@{{ domain }}"
    
    # If True will uninstall and purge existing applications and configurations
    # DO NOT USE THIS IN PRODUCTION ENVIRONMENT
    purge: true
    
    # if idp and sp have the same ip: apache's <VirtualHost ip:port> must be configured as <VirtualHost *:port>
    # otherwise exception "[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)" will be raised
    # otherwise exception SSL_ERROR_RX_RECORD_TOO_LONG will be raised or other, exception message depends by the client.
    ldap_ip:  "192.168.3.63"
    idp_ip:   "{{ ldap_ip }}" # everything on the same vm
    sp_ip:    "{{ ldap_ip }}"

    # Commons
    cert_path: "/etc/ssl/certs/{{ domain }}"
    tmp_upload_dir: "/tmp/ansible-shibboleth-idp-sp-setup"

    # LDAP configuration
    ldap_fqdn: "ldap.testunical.it"
    ldap_basedc: "dc={{ domain2 }},dc={{ domain1 }}"
    ldap_binddn: "uid=idp,ou=applications,{{ ldap_basedc }}"
    ldap_pw: idpsecret
    ldap_basedn: "ou=people,{{ ldap_basedc }}"
    # remember to copy slapds' public cert, as slapd-cert.pem, in roles/common/files/certs/
    ldap_cert: slapd-cert.pem
    
    # Servlet configuration
    servlet_container: tomcat
    servlet_ram: 384m
    # Jetty configuration
    jetty_distribution: jetty-distribution-9.4.8.v20171121
    jetty_pkg: "{{ jetty_distribution }}.tar.gz"
    jetty_path : /opt/jetty
    # Tomcat configuration
    tomcat_version: tomcat8
    # tomcat_admin_pw: tomcatsecret
    # tomcat_manager_pw: tomcatsecret

    # Shibboleth IDP
    shib_idp_version: "3.3.2"
    shib_idp_package: "shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
    shib_dest_dir: "/opt"
    idp_path: "{{ shib_dest_dir }}/shibboleth-idp"
    shib_setup_folder: "{{ shib_dest_dir }}/shibboleth-identity-provider-{{ shib_idp_version }}"
    idp_dl_url: "https://shibboleth.net/downloads/identity-provider/{{ shib_idp_version }}/{{ shib_idp_package }}"
    idp_web_folder: /idp/shibboleth
    idp_entity_id: "https://{{ idp_fqdn }}{{ idp_web_folder }}"
    idp_fqdn: "idp.{{ domain }}"
    idp_secret: idpsecret
    idp_admin_email: "root@{{ idp_fqdn }}"
    idp_attr_resolver: attribute-resolver-full.v332.xml # in roles/shib2_configure/files
    # TODO: Error creating bean with name 'shibboleth.AccessControlPolicies': Cannot create inner bean 'shibboleth.IPRangeAccessControl$child#4f0c1409'
    # idp_status_acl: "192.168.3.34/24, 192.168.27.72/24"
    idp_disable_saml1: true
    
    # persistent id on rdbms, it will install mariadb
    idp_local_storage: false
    
    # Shibboleth IDP RDBMS per persistentID
    idp_rdbms_dbname: shibboleth
    idp_rdbms_user: "{{ idp_rdbms_dbname }}"
    idp_rdbms_pw: "{{ idp_secret }}"

    # Shibboleth SP
    sp_fqdn: "sp.{{ domain }}"

  roles:   
    # apt dependencies and certificates
    - { role: common, tags: ["common"] }
    - { role: shib3idp_install, tags: ["shib3idp_install"] }
    
    # TODO: decouple idp tasks and sp tasks in apache2
    - { role: apache2, tags: ["apache2"] }
    
    # shibboleth-idp only configuration
    - { role: shib3idp_configure, tags: ["shib3idp_configure"] }
    
    # service provider setup
    - { role: mod-shib2, tags: ["shib2"] }  
