- name: Install libapache2-mod-shib2
  apt: name=libapache2-mod-shib2 state=present

- name: Create Shibboleth SP keys
  shell: /usr/sbin/shib-keygen -f -h {{ sp_fqdn }} -e https://{{ sp_fqdn }}/shibboleth

- file:
    glob: "/etc/shibboleth/sp-key.pem"
    owner: _shibd
    group: "{{ servlet_container }}"
    mode: 0640
  when: servlet_container == "jetty"

- file:
    path: "/etc/shibboleth/sp-key.pem"
    owner: _shibd
    group: "{{ tomcat_version }}"
    mode: 0640
  when: servlet_container == "tomcat"

- file:
    path: "/etc/shibboleth/sp-cert.pem"
    owner: _shibd
    group: _shibd
    mode: 0644

# 2018-03-04 00:53:22 ERROR OpenSSL : error code: 537346050 in bss_file.c, line 408
# 2018-03-04 00:53:22 CRIT Shibboleth.Application : error building CredentialResolver: Unable to load private key from file (/etc/shibboleth/sp.testunical.it-key.pem).
# - name: Copy Shibboleth SP certs
  # copy: 
    # src: "{{ item }}"
    # dest: "/etc/shibboleth/"
    # owner: root
    # group: ssl-cert
    # mode: 640
  # with_fileglob:
    # - roles/common/files/certs/{{ sp_fqdn }}-key.pem
    # - roles/common/files/certs/{{ sp_fqdn }}-cert.pem

- name: Create metadata directory for IdP metadata
  file: name=/etc/shibboleth/metadata state=directory

- name: Configure Shibboleth SP
  template:
    src: roles/mod-shib2/templates/shibboleth2.xml
    dest: /etc/shibboleth/shibboleth2.xml
    backup: yes

- name: Configure Shibboleth SP Attribute Map
  copy:
    src: roles/mod-shib2/files/attribute-map.xml
    dest: /etc/shibboleth/attribute-map.xml
    backup: yes

# METADATAS
- name: Add SP {{ sp_fqdn }} Metadata to Shibboleth IdP
  get_url:
    url: https://{{ sp_fqdn }}/Shibboleth.sso/Metadata
    dest: "{{ idp_path }}/metadata/{{ sp_fqdn }}-metadata.xml"
    validate_certs: no
    force: yes

- name: Register SP into Shibboleth IdP's metadata-providers.xml
  template:
    src: roles/shib3idp_configure/templates/metadata-providers.xml
    dest: "{{ idp_path }}/conf/metadata-providers.xml"
    backup: yes

- name: Cleanup old Shibboleth IdP metadata from SP
  file: path="/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml" state=absent
  when: cleanup is defined

- name: Add IdP Metadata to SP (/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml)
  get_url:
    url: "{{ idp_entity_id }}"
    dest: "/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml"
    validate_certs: no
    force: yes
    
- name: Restart shibd
  service: name=shibd state=restarted enabled=yes

- name: Restart Jetty
  service: name="jetty" state=restarted enabled=yes
  when: servlet_container == "jetty"

- name: Restart Tomcat
  service: name="{{ tomcat_version }}" state=restarted enabled=yes
  when: servlet_container == "tomcat"
# END METADATAS
