- name: Install libapache2-mod-shib2
  apt: name=libapache2-mod-shib2 state=present

# this must be done, general purpose certificates will not works -> ERROR OpenSSL : error code: 537346050 in bss_file.c, line 408
- name: Create Shibboleth SP keys
  shell: /usr/sbin/shib-keygen -f -h {{ sp_fqdn }} -e https://{{ sp_fqdn }}/shibboleth

- file:
    glob: "/etc/shibboleth/sp-key.pem"
    owner: _shibd
    group: "{{ servlet_container }}"
    mode: 0640
  when: servlet_container == "jetty"

- file:
    path: "/etc/shibboleth/sp-key.pem"
    owner: _shibd
    group: "{{ tomcat_version }}"
    mode: 0640
  when: servlet_container == "tomcat"

- file:
    path: "/etc/shibboleth/sp-cert.pem"
    owner: _shibd
    group: _shibd
    mode: 0644

- name: Create metadata directory for IdP metadata
  file: name=/etc/shibboleth/metadata state=directory

- name: Configure Shibboleth SP
  template:
    src: roles/mod-shib2/templates/shibboleth2.xml
    dest: /etc/shibboleth/shibboleth2.xml
    backup: yes

- name: Configure Shibboleth SP Attribute Map
  copy:
    src: roles/mod-shib2/files/attribute-map.xml
    dest: /etc/shibboleth/attribute-map.xml
    backup: yes

- name: Restart Jetty
  service: name="jetty" state=restarted enabled=yes
  when: servlet_container == "jetty"

- name: Restart Tomcat
  service: name="{{ tomcat_version }}" state=restarted enabled=yes
  when: servlet_container == "tomcat"

# METADATAS - IDP FIRST
- name: Register SP into Shibboleth IdP's metadata-providers.xml
  template:
    src: roles/shib3idp_configure/templates/metadata-providers.xml
    dest: "{{ idp_path }}/conf/metadata-providers.xml"
    backup: yes

- name: Add SP {{ sp_fqdn }} Metadata to Shibboleth IdP
  get_url:
    url: https://{{ sp_fqdn }}/Shibboleth.sso/Metadata
    dest: "{{ idp_path }}/metadata/{{ sp_fqdn }}-metadata.xml"
    validate_certs: no
    force: yes

- name: Restart Jetty
  service: name="jetty" state=restarted enabled=yes
  when: servlet_container == "jetty"

- name: Restart Tomcat
  service: name="{{ tomcat_version }}" state=restarted enabled=yes
  when: servlet_container == "tomcat"

# METADATAS - SP

# reboot time (thank you servlet_container) makes metadata GET fails or return 404!
- name: sleep for 10 seconds to let servlet reboot and make its bootstrap assessments
  wait_for: timeout=10

- name: Cleanup old Shibboleth IdP metadata from SP
  file: path="/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml" state=absent
  when: cleanup is defined

- name: Add IdP Metadata to SP (/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml)
  get_url:
    url: "{{ idp_entity_id }}"
    dest: "/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml"
    validate_certs: no
    force: yes

- name: Restart shibd
  service: name=shibd state=restarted enabled=yes

# END METADATAS
