# TOMCAT
- name: Stop {{ tomcat_version }}
  service: name={{ tomcat_version }} state=stopped enabled=false
  #~ ignore_errors: yes

- name: Uninstall {{ tomcat_version }}
  apt: name={{ tomcat_version }} state=absent purge=yes
  # when: cleanup is defined

# to improve security read this: https://www.owasp.org/index.php/Securing_tomcat
- name: Remove /etc/tomcat*
  file: path=/etc/tomcat* state=absent

# SHIBBOLETH
- name: Cleanup Shibboleth IdP Install
  file: path="{{ idp_path }}" state=absent

# TODO
# RIMUOVERE I CERTIFICATI QUI

# MYSQL
- name: Stop mysql-server
  service: name=mysql-server state=stopped enabled=false
  # when: cleanup is defined
  #~ ignore_errors: yes

- name: Uninstall {{ tomcat_version }}
  apt: name={{ tomcat_version }} state=absent purge=yes

- name: Uninstall libapache2-mod-shib2
  apt: name=libapache2-mod-shib2 state=absent purge=yes

- name: Remove /etc/shibboleth dir
  file: path=/etc/shibboleth state=absent
  when: cleanup is defined
