# TOMCAT
- name: Stop {{ tomcat_version }}
  service: name={{ tomcat_version }} state=stopped enabled=false
  # when: cleanup is defined
  #~ ignore_errors: yes

- name: Uninstall {{ tomcat_version }}
  apt: name={{ tomcat_version }} state=absent purge=yes
  # when: cleanup is defined

# to improve security takeh this: https://www.owasp.org/index.php/Securing_tomcat
- name: Remove /etc/tomcat*
  file: path=/etc/tomcat* state=absent
  # when: cleanup is defined

# SHIBBOLETH
- name: Cleanup Shibboleth IdP Install
  file: path="{{ idp_path }}" state=absent

# RIMUOVERE I CERTIFICATI QUI

# MYSQL
- name: Stop mysql-server
  service: name=mysql-server state=stopped enabled=false
  # when: cleanup is defined
  #~ ignore_errors: yes

- name: Uninstall {{ tomcat_version }}
  apt: name={{ tomcat_version }} state=absent purge=yes
  # when: cleanup is defined
