- name: Update apt cache
  apt: update_cache=yes
  # apt: update_cache=yes cache_valid_time=86400
  tags: online

- name: Install apt packages
  apt: name={{ item }} state=present
  with_items:
    - libmysql-java #contains: /usr/share/java/mysql.jar
    - html2text
    - emacs24-nox
    - vim
    - ntp
    - apache2
    - openjdk-8-jre
    - "{{ tomcat_version }}"
    - libapache2-mod-shib2
    - libapache2-mod-php7.0
  tags: online

- name: Configure /etc/hosts
  template: 
    src: roles/common/templates/hosts 
    dest: /etc/hosts

- name: get JAVA_HOME
  shell: readlink -f /usr/bin/java | sed "s:bin/java::"
  register: java_home

- name: Configure /etc/environment
  template: src=roles/common/templates/environment dest=/etc/environment

- name: "Ensures {{ cert_path }} dir exists"
  file: path="{{ cert_path }}" state=directory

- name: Copy certs
  copy: 
    src: "{{ item }}"
    dest: "{{ cert_path }}/"
    owner: root
    group: ssl-cert
    mode: 640
  with_fileglob:
    - roles/common/files/certs/*

- name: "Ensures {{ tmp_upload_dir }} dir exists"
  file: path="{{ tmp_upload_dir }}" state=directory
