- name: Generate salt for persistentId generator
  shell: openssl rand -base64 36
  register: persId_salt
  when: persId_salt is not defined

- name: jetty user for idp dirs
  file: name="{{ item }}" owner="jetty" recurse=yes
  with_items:
    - "{{ idp_path }}/conf"
    - "{{ idp_path }}/logs"
    - "{{ idp_path }}/metadata"
    - "{{ idp_path }}/credentials"
  
- name: Install the IdP WAR
  template: 
    src: roles/shib3idp_configure/templates/idp.xml 
    dest: "{{ jetty_path }}/webapps/idp.xml"
  
- name: Configure LDAP Auth
  template: 
    src: roles/shib3idp_configure/templates/ldap.properties 
    dest: "{{ idp_path }}/conf/ldap.properties" 
    
- name: Configure Enhanced Logging
  copy: 
    src: roles/shib3idp_configure/files/logback.xml 
    dest: "{{ idp_path }}/conf/logback.xml"

# the sourceAttribute MUST BE an attribute, or a list of comma-separated attributes, that uniquely identify the subject of the generated persistent-id. It MUST BE: Stable, Permanent and Not-reassignable
- name: Configure saml-nameid.properties (dataStore and persistentId)
  template: 
    src: roles/shib3idp_configure/templates/saml-nameid.properties 
    dest: "{{ idp_path }}/conf/saml-nameid.properties" 

- name: Configure saml-nameid.xml (persistentId)
  copy: 
    src: roles/shib3idp_configure/files/saml-nameid.xml
    dest:  "{{ idp_path }}/conf/saml-nameid.xml"

# Remove the comment to the bean called "c14n/SAML2Persistent"
- name: Configure subject-c14n.xml (persistentId)
  copy: 
    src: roles/shib3idp_configure/files/subject-c14n.xml
    dest:  "{{ idp_path }}/conf/c14n/subject-c14n.xml"
 
- name: Configure relying-party.xml (persistentId)
  template:
    src: roles/shib3idp_configure/templates/relying-party.xml
    dest:  "{{ idp_path }}/conf/relying-party.xml"

- name: Configure global.xml (dataStore and persistentId)
  template:
    src: roles/shib3idp_configure/templates/global.xml
    dest:  "{{ idp_path }}/conf/global.xml"

- name: Configure IdP attribute-filter.xml 
  template: 
    src: roles/shib3idp_configure/templates/attribute-filter.xml
    dest: "{{ idp_path }}/conf/attribute-filter.xml"

# wget http://www.garr.it/idem-conf/attribute-resolver-v3-idem.xml -O /opt/shibboleth-idp/conf/attribute-resolver-v3-idem.xml
- name: Copy configured attribute-resolver-v3-idem.xml in attribute-resolver.xml
  copy: 
    src: roles/shib3idp_configure/files/attribute-resolver-v3-idem.xml
    dest: "{{ idp_path }}/conf/attribute-resolver.xml"

# - name: Add attribute-resolver.xml to services.xml
  # copy: 
    # src: roles/shib3idp_configure/files/services.xml
    # dest: "{{ idp_path }}/conf/services.xml"

- name: Add metadata providers
  template: 
    src: roles/shib3idp_configure/templates/metadata-providers.xml-no_sp
    dest: "{{ idp_path }}/conf/metadata-providers.xml"

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: '<IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0">'
    replace: '<IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">'
    backup: yes

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: '<ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding" Location="https://{{ idp_fqdn }}:8443/idp/profile/SAML1/SOAP/ArtifactResolution" index="1"/>'
    replace: ''
    backup: yes

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: '/idp/profile/SAML2/SOAP/ArtifactResolution" index="2"'
    replace: '/idp/profile/SAML2/SOAP/ArtifactResolution" index="1"'
    backup: yes

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: '<AttributeAuthorityDescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol">'
    replace: '<AttributeAuthorityDescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">'
    backup: yes

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: '<AttributeService Binding="urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding" Location="https://{{ idp_fqdn }}:8443/idp/profile/SAML1/SOAP/AttributeQuery"/>'
    replace: ''
    backup: yes

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: '<!-- <AttributeService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://{{ idp_fqdn }}:8443/idp/profile/SAML2/SOAP/AttributeQuery"/> -->'
    replace: '<AttributeService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://{{ idp_fqdn }}:8443/idp/profile/SAML2/SOAP/AttributeQuery"/>'
    backup: yes

- replace:
    path: "{{ idp_path }}/metadata/idp-metadata.xml"
    regexp: ':8443'
    replace: ''
    backup: yes

- name: Restart Jetty
  service: name="jetty" state=restarted
